### ISSUE TITLE
Shards management troubles

### ISSUE THREAD

**Issue by PierrotIV** [robert388/Necrosis-classic#108]
Hi,
My Necrosis is configured to move shards in my shard bag and destroy them once the bag is full.
I have two misbehaviours when creating a shard while the shard is full:
- it just does not destroy it
- it tries moving it (exchange with another in the bag I guess) and enters an endless ding sound cycle which prevent using anything
Regards

**Comment by urnati** [comment]
This is working for me with a 'Soul Pouch' and bag space.
Are your bags full when this happens? What shard bag? Going into / out of combat? Do you have multiple shard bags? 
Is the 'Selection of Soul Shard Container' set to the right bag slot? Do you also use the 'Max number of shards'?
Any other details may help.

**Comment by PierrotIV** [comment]
Hi,
Not all bags are full when this happens.
I use a felcloth bag. This one is full when the problem occurs.
Last time it happened, the 25th shard had not been deleted during combat and I used my hearthstone to go back in town. Once arrived, it started its endless ding cycle.
The selection of soul shard container is on bag 5 and it is the appropriate one.
I do not use the max number of shards.

Last detail : it worked in 5.3.

Same thing happens to my son with his 46 Warlock on another computer / account with same settings.

Regards

**Comment by PierrotIV** [comment]
Fixed in 6.4
