### ISSUE TITLE
Healthstone and Soulstone ranks broken again

### ISSUE THREAD

**Issue by Nezz** [robert388/Necrosis-classic#109]
After the latest update to version 6.1, the Healthstone and Soulstone ranks being cast are wrong again.

Instead of creating Healthstone (Major):
- Left clicking the Healthstone button creates Healthstone
- Right clicking the Healthstone button creates Healthstone (Greater)
Probably as a side effect, the mana requirement is displayed for Healthstone (Greater)

Instead of creating Soulstone (Major):
- Left clicking the Soulstone button creates Soulstone 
- Right clicking the Soulstone button creates Soulstone (Lesser)

Downgrading to V5.3 fixes the issue.

**Comment by saraneth0o** [comment]
Same problem. Is there a way to fix this?

**Comment by urnati** [comment]
Creating health / soul stones (right-click) should be correct in 6.2.

Left click *uses* a stone - correct?

**Comment by urnati** [comment]
6.3 fixed this at least for EN. I am working an issues causing this in other translations.
I'll close this in a couple days if there are no updates here to the contrary.

**Comment by Nezz** [comment]
Indeed it's fixed now. Thanks!
