### ISSUE TITLE
UPDATE: After pressing reload UI, it seems to to be working now! But still need to fix the startup error

### ISSUE THREAD

**Issue by Kinkz** [robert388/Necrosis-classic#11]
Message: Interface\AddOns\Necrosis\Timers\Functions.lua:199: bad argument #1 to 'pairs' (table expected, got nil)
Time: Wed Jun  5 16:42:54 2019
Count: 1
Stack: Interface\AddOns\Necrosis\Timers\Functions.lua:199: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
Interface\AddOns\Necrosis\Timers\Functions.lua:199: in function `getManaCostForSpell'
Interface\AddOns\Necrosis\Necrosis.lua:2235: in function `SpellSetup'
Interface\AddOns\Necrosis\Initialize.lua:100: in function `Initialize'
Interface\AddOns\Necrosis\Necrosis.lua:341: in function `OnLoad'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

Also the /necrosis command is not working. 
![3333](https://user-images.githubusercontent.com/5814151/58989169-641b9080-87b1-11e9-84a7-020ec9252af2.JPG)

**Comment by robert388** [comment]
Should be fixed in latest version!
