### ISSUE TITLE
BROKEN after last update.

### ISSUE THREAD

**Issue by andrehsmendes** [robert388/Necrosis-classic#110]
Addon is not tracking, showing any visual info.

-- Clicking Show Digital Counter -> start showing what was not showing initially.

NOTE: I removed all files and all saved variables. Still having the problem.

**Comment by Zortt** [comment]
same after updating it is not working anymore this is sad

**Comment by urnati** [comment]
Do you mean the counter showing 00 in the main sphere? And the sphere may not be there but the other icons are?
If so, a log out / in works for me. Not ideal but hope that helps until a fix is found. 
This just started to happen to me in the couple days.

**Comment by andrehsmendes** [comment]
The middle completely desappear, nothing is getting tracked.

**Comment by andrehsmendes** [comment]
Still not working.... same issue. nothing is getting tracked.

**Comment by urnati** [comment]
6.3 fixed this so I'll close this in a couple days if there are no updates here to the contrary.
