### ISSUE TITLE
Completely broken for all of 6.x versions

### ISSUE THREAD

**Issue by DaveJ61** [robert388/Necrosis-classic#115]
Oops, looks like I have duplicated the issue. Please delete if not required.

Tried installing as requested by completely removing everything, including the stuff in the savedvariables directory. I still get the following with any version 6. I am using the version 5 without any issues at all.

Date: 2020-01-23 18:34:57
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Necrosis\Necrosis.lua line 1513:
   attempt to compare number with nil
Debug:
   Necrosis\Necrosis.lua:1513: UpdateMana()
   Necrosis\Initialize.lua:118: Initialize()
   Necrosis\Necrosis.lua:436: OnEvent()
   Necrosis\Localization.lua:38:
      Necrosis\Localization.lua:31
Locals:
self = <table> {
 RezTimerUpdate = <function> defined @Interface\AddOns\Necrosis\Timers\OtherTimers.lua:14
 Unit = <table> {
 }
 InsertTimerParTable = <function> defined @Interface\AddOns\Necrosis\Timers\Functions.lua:16
 ButtonSetup = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:2062
 Timer_Click = <function> defined @Interface\AddOns\Necrosis\XML\Options-Timers.lua:163
 Localize = <table> {
 }
 SoulshardSwitch = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:1998
 FindSlot = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:2024
 Localization_Speech_Es = <function> defined @Interface\AddOns\Necrosis\Speech\Speech-es.lua:37
 BuffVector_Click = <function> defined @Interface\AddOns\Necrosis\XML\Options-Menus.lua:761
 SetCompanionPage = <function> defined @Interface\AddOns\Necrosis\XML\Options-Buttons.lua:520
 CreateGroup = <function> defined @Interface\AddOns\Necrosis\Timers\GraphicalTimers.lua:14
 Msg = <function> defined @Interface\AddOns\Necrosis\Message.lua:12
 AddFrame = <function> defined @Interface\AddOns\Necrosis\Timers\GraphicalTimers.lua:83
 HealthstoneCooldown = "Necrosis"
 InCombatAttribute = <function> defined @Interface\AddOns\Necrosis\XML\Attributes.lua:496
 RetraitTimerParGuid = <function> defined @Interface\AddOns\Necrosis\Timers\Functions.lua:283
 BuffSpellAttribute = <function> defined @Interface\AddOns\Necrosis\XML\Attributes.lua:178
 DemonVector_Init = <function> defined @Interface\AddOns\Necrosis\XML\Options-Menus.lua:779
 ShowAntiFearWarning = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:2547
 MenuAttribute = <function> defined @Interface\AddOns\Necrosis\XML\Attributes.lua:79
 CreateWarlockUI = <function> defined @Interface\AddOns\Necrosis\XML\XML.lua:42
 GetCompanionInfo = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:3079
 Event_Init = <function> defined @Interface\AddOns\Necrosis\XML\Options-Sphere.lua:214
 Speech_It = <function> defined @Interface\AddOns\Necrosis\Message.lua:130
 SetTimersConfig = <function> defined @Interface\AddOns\Necrosis\XML\Options-Timers.lua:14
 Event_Click = <function> defined @Interface\AddOns\Necrosis\XML\Options-Sphere.lua:226
 UnitHasBuff = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:2528
 Spell_Init = <function> defined @Interface\AddOns\Necrosis\XML\Options-Sphere.lua:236
 Frame_Prefix = "Necrosis"
 SetMessagesConfig = <function> defined @Interface\AddOns\Necrosis\XML\Options-Messages.lua:14
 StoneAttribute = <function> defined @Interface\AddOns\Necrosis\XML\Attributes.lua:333
 BuildTooltip = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:1003
 UpdateHealth = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:1460
 Translation = <table> {
 }
 SymetrieTimer = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:2980
 ManaCostLocalize = <function> defined @Interface\AddOns\Necrosis\Spells.lua:483
 ChangeDemon = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:725
 Speech = <table> {
 }
 Localization_Speech_Ru = <function> defined @Interface\AddOns\Necrosis\Speech\Speech-ru.lua:38
 CreateSpellList = <function> defined @Interface\AddOns\Necrosis\Spells.lua:276
 ChatMessage = <table> {
 }
 CreateMenuCurse = <function> defined @Interface\AddOns\Necrosis\XML\XML.lua:356
 SpellSetup = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:2229
 Sound = <table> {
 }
 Tri = <function> defined @Interface\AddOns\Necrosis\Timers\Functions.lua:380
 CreateMenuPet = <function> defined @Interface\AddOns\Necrosis\XML\XML.lua:324
 Frame_Prefix_Pet = "NecrosisPetMenu"
 UpdateMana = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:1484
 Warlock_Buttons = <table> {
 }
 Initialize_Speech = <function> defined @Interface\AddOns\Necrosis\Initialize.lua:13
 RankToStone = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:2168
 TradeStone = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:2609
 OnDragStart = <function> defined @Interface\AddOns\Necrosis\Necrosis.lua:983
 OnDragStop = <function> defined @Interface\AddOns\Necrosis\Necrosis
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ArkInventory, v30913
  ArkInventoryRules, v20000
  ArkInventorySearch, v20000
  Armory, vv1.6.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoCancelGhostWolf, v1.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  Carbonite, v@project-version@
  CarboniteNotes, v@project-version@
  CarboniteQuests, v@project-version@
  CarboniteSocial, v@project-version@
  CarboniteWarehouse, v@project-version@
  ClassicArmory, v0.2
  DBMCore, v1.13.30
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DuelResponseBlacklistClassic, v
  DuelResponseClassic, v1.0.19-Classic
  DuelResponseWhisperClassic, v
  DungeonFinder, v0.1.7
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FasterLooting, v1.1.2
  FishingBuddy, v0.7.3 Beta 2
  FriendsListPlus, v0.4
  GTFO, v4.52
  IHearYouAll, v4.5
  Informant, v8.2.6374 (SwimmingSeadragon)
  LFG, v1.4.2
  Molinari, v80300.65-Release
  Necrosis, v6.2
  orbSellAndRepair, v1.0.1
  Pawn, v2.3.18
  Recount, vv1.13.3b
  ReloadUiButton, v8.2.0-final
  SexyMap, vv5-classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.1.5.11303
  TitanClassicAmmo, v1.1.5.11303
  TitanClassicBag, v1.1.5.11303
  TitanClassicClock, v1.1.5.11303
  TitanClassicGold, v1.1.5.11303
  TitanClassicGuild, v1.0.0.3
  TitanClassicLocation, v1.1.5.11303
  TitanClassicLootType, v1.1.5.11303
  TitanClassicPerformance, v1.1.5.11303
  TitanClassicRecZone, v1.0.0.5
  TitanClassicRegen, v1.1.5.11303
  TitanClassicRepair, v1.1.5.11303
  TitanClassicVolume, v1.1.5.11303
  TitanClassicXP, v1.1.5.11303
  TitanProfessionsMulti, v1.4
  TitanReputations, vv1.1-classic
  TitanSocial, v1.13.3
  TomTom, vv11303-1.0.9
  WideQuestLog, v
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=863)

**Comment by DaveJ61** [comment]
I can add further that I have tried all the suggestions you have given by deleting the config files in the acount directory etc, but this still does not work. The sphere is empty and does not update and also throws the above when I log in. Tried all 6.x versions and the same deal. I am currently using the 5.3 without issues.

**Comment by urnati** [comment]
6.3 at least made this better, is it working for you now?

**Comment by DaveJ61** [comment]
Hi, I haven't played for a few days but all working fine now thank you very much.
