### ISSUE TITLE
Purchased Drain Life rank 2 and got this error

### ISSUE THREAD

**Issue by KunoNoOni** [robert388/Necrosis-classic#12]
Message: Interface\AddOns\Necrosis\Necrosis.lua:581: bad argument #1 to 'ipairs' (table expected, got nil)
Time: Fri Jun  7 22:22:09 2019
Count: 1
Stack: Interface\AddOns\Necrosis\Necrosis.lua:581: bad argument #1 to 'ipairs' (table expected, got nil)
[C]: in function `ipairs'
Interface\AddOns\Necrosis\Necrosis.lua:581: in function `OnEvent'
Interface\AddOns\Necrosis\XML\XML.lua:152: in function <Interface\AddOns\Necrosis\XML\XML.lua:145>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by KunoNoOni** [comment]
Hmm.. it happened again when I learned Create Healthstone (Lesser). it might just be an issue with training new skills

**Comment by robert388** [comment]
@KunoNoOni Thanks will fix during stress test
