### ISSUE TITLE
After new update you can't perfectly align buttons

### ISSUE THREAD

**Issue by fagitomania** [robert388/Necrosis-classic#120]
![Screenshot_164](https://user-images.githubusercontent.com/58953642/79637077-d3f5f800-8184-11ea-9d17-b4386f6b0e45.png)
This wasn't happening before. I could select in sphere rotation 258 for example, now it only rotates by jumps of 5, for example 250 then 255, cant select in between.

**Comment by DevineLykan** [comment]
you can manually move these if you unlock necrosis to get them where you want as a work around
