### ISSUE TITLE
Sphere Resets Every Time

### ISSUE THREAD

**Issue by DevineLykan** [robert388/Necrosis-classic#122]
The Necrosis Button size resets every reload or when I start the game. Though the size setting is still the same, when you do change the size the sphere moves to a new location...
![Untitled](https://user-images.githubusercontent.com/46081455/79692435-13901300-825d-11ea-91ff-2830133cbf66.png)
![Untitled](https://user-images.githubusercontent.com/46081455/79692444-26a2e300-825d-11ea-96c8-3ef0653e427f.png)

**Comment by PESLDK** [comment]
Same for me, the "Hidden" buttons move as well.

**Comment by rogkar** [comment]
Same for me! Every time I die, or reload, or something the sphere becomes large and at another point on the screen. It's very annoying...

**Comment by mrtroubles007** [comment]
Can you please update this mod, its brokennnnnnn, mine is doing same thing these guys above is doing.
