### ISSUE TITLE
Soulstone doesnt create one

### ISSUE THREAD

**Issue by fagitomania** [robert388/Necrosis-classic#124]
Its random. Sometimes it creates a soulstone, sometimes it doesnt. I need to open the spellbook.
Adding features is nice but breaking the addon with every update is not

**Comment by fagitomania** [comment]
I got some more feedback on this. This behavior is 100% reproducable. It happens if you bind a macro to cast sousltone and then try to create a new one from the addon.
For example i use a macro to cast soulstone on raids because i have my own custom output text. If i don't cast soul ressurection with necrosis and use my macro, the next time i click on necrosis soulstone button to create one nothing happens. I need to relog to solve it.

**Comment by DevineLykan** [comment]
can confirm this issue, looks like in necrosis.lua it's treating the soulstone action the same as when creating one, there is no differentiation in the code for the two events as it was before the recode.

**Comment by fagitomania** [comment]
This happened on a older update as well and took some time to fix

**Comment by DevineLykan** [comment]
Fixed in latest version, you can close this issue.
