### ISSUE TITLE
*REQUEST* Make it so that we can change speeches

### ISSUE THREAD

**Issue by fagitomania** [robert388/Necrosis-classic#127]
Especially soulstone one, i want my custom message like a macro would do

**Comment by DevineLykan** [comment]
Edit the Speech-en or the equiv for your language. You can edit the speeches in there.

**Comment by fagitomania** [comment]
> Edit the Necrosis/Speech-en.lua or the equiv for your language. You can edit the speeches in there.
> 
> You can open it with notepad if you don't have Luaedit2010 (which is free)

Can i put {Diamond}, for example, in it as well so it shows the wow marks?

**Comment by DevineLykan** [comment]
{ } is a command that lua uses, but it might work, I can't test, as no speeches work for me on 7.1. Nothing happens and I get no lua errors so no idea what's going on xD

**Comment by DevineLykan** [comment]
close this ticket if you were able to edit the speeches as advised

**Comment by fagitomania** [comment]
I didn't manage to make it work so i will stick out to my macro. I will forward in the future if you can make it so that we have custom speeches from the addon
