### ISSUE TITLE
Corruption timer is not accurate 

### ISSUE THREAD

**Issue by JulianNorton** [robert388/Necrosis-classic#14]
![image](https://user-images.githubusercontent.com/2412992/62822783-18d98180-bb56-11e9-8361-524fb0585029.png)

Rank 1 corruption is 12 seconds, but the dot timer shows 20 seconds.

**Comment by robert388** [comment]
Great picture, found the issue will update the addon before the 26th.

**Comment by robert388** [comment]
Fixed with https://github.com/robert388/Necrosis-classic/releases/tag/v0.6
Multiple spells where affected by this :)

**Comment by JulianNorton** [comment]
Thank you! closing as fixed.
