### ISSUE TITLE
Second spell timer does not reset on target death

### ISSUE THREAD

**Issue by Keodo** [robert388/Necrosis-classic#15]
The timer for Immolate (currently rank 1 for me) does not stop counting down when the target dies. Corruption and Curse of Weakness seem to be working properly.
![WoWScrnShot_081119_083752](https://user-images.githubusercontent.com/53997097/62833892-813a6880-bc13-11e9-92ac-1da05a7d17bd.jpg)

**Comment by Keodo** [comment]
Update: At first I was using Corruption then Immolate and was getting this problem. I swapped the spells, so Immolate then Corruption and now the problem is with Corruption. It seems it's the second spell timer that has the problem, not necessarily the spell itself.
![WoWScrnShot_081119_091958](https://user-images.githubusercontent.com/53997097/62834395-8c909280-bc19-11e9-8aed-5c89550303a8.jpg)
![WoWScrnShot_081119_091952](https://user-images.githubusercontent.com/53997097/62834396-8c909280-bc19-11e9-82a6-a5c4d62a2cd4.jpg)

**Comment by robert388** [comment]
Hopefully fixed in next release, bit hard to debug without classic client working =]

**Comment by robert388** [comment]
Hopefully fixed with https://github.com/robert388/Necrosis-classic/releases/tag/v0.6

**Comment by Keodo** [comment]
Thanks for all your hard work getting this ready for launch and the quick response!
