### ISSUE TITLE
Soulstone / Healthstone Ranks not working

### ISSUE THREAD

**Issue by Xerxes13** [robert388/Necrosis-classic#22]
The ranks for the stones doesnt seem to work. I'm Lvl 18 and have "Create Soulstone (Minor)", however, the button on the sphere doesnt work (left or right click). If I change the SpellID in Spells.lua to the Minor version (ID 693), the button works fine.

Same with Healthstone. I can create a Healthstone (Minor), but with a left click instead of a right click on the sphere button.

Thanks
Love the addon and ur work. much appreciated

**Comment by cerka** [comment]
this PR should fix it
https://github.com/robert388/Necrosis-classic/pull/26
can you try https://github.com/cerka/Necrosis-classic/tree/fix/stone-localisation
(i will change the create soulstone spell id this evening)

**Comment by Xerxes13** [comment]
Now I only create an Minor Healthstone, but I have learned the Lesser version

**Comment by cerka** [comment]
so it only create a minor healthstone while you have a bigger one aviable?
thank you, i'll check that

**Comment by robert388** [comment]
Thanks guys. The codebase is a dirty mess. 
A rework of the spell detection mechanic will probably end up in a rewrite.
I merged the fixes.

**Comment by demidieu** [comment]
in french version, the buttons Healthstone/Soulstone doesnt  display.(i'm level 33)

**Comment by demidieu** [comment]
![Capture necrosis](https://user-images.githubusercontent.com/55031896/64479489-ee470c80-d185-11e9-9979-9c7c597d8b4b.PNG)
