### ISSUE TITLE
Addon not working at all for me

### ISSUE THREAD

**Issue by HexCode21** [robert388/Necrosis-classic#43]
I get this issues, I tried deleting files in WTF folder and didn't help. 

Date: 2019-09-24 19:19:53
ID: 1
Error occured in: Global
Count: 1
Message: [string "Necrosis_Variable_Frame:OnLoad"] line 1:
   attempt to index global 'this' (a nil value)
Debug:
   [string "*:OnLoad"]:1:
      [string "*:OnLoad"]:1
Locals:
self = Necrosis_Variable_Frame {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'this' (a nil value)"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasDungeonLocs, vv1.45.00.11302.01
  AtlasLootClassic, vv1.1.12
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.13
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  ClassicLFG, v1.0.0
  ClassicThreatMeter, v1.08
  DBMCore, v1.13.12
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1302r026
  Details, v
  DetailsTinyThreat, v
  FishingBuddy, v0.5 Beta 1
  GatherMate2, v1.45
  MapCoords, v1.4
  Necrosis, v3.0 (r225)
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=402)

**Comment by HexCode21** [comment]
I uninstalled/reinstalled twice, delete WTF files and now it works!!! :D

**Comment by robert388** [comment]
Cool man!
