### ISSUE TITLE
Fr - classic - detect invisibility rank

### ISSUE THREAD

**Issue by PierrotIV** [robert388/Necrosis-classic#53]
Hi,

I use french classic client.
Detect invisibility does not upgrade, I know lesser, "standard" and greater and the add-on keeps showing lesser.

Regards

**Comment by DevineLykan** [comment]
[Bindings.zip](https://github.com/robert388/Necrosis-classic/files/3801479/Bindings.zip)

Fixed in these lua's. I've also fixed Summon Infernal and Enslave Demon

**Comment by PierrotIV** [comment]
Hi @DevineLykan 
Thank you for the fix, that works :)
Do you have an idea for the major stones ?
Regards

**Comment by DevineLykan** [comment]
Stones? My health stones and soul stones are correct when i check them in my bag, got an example of it being wrong and I'll see if i can see a cause.

**Comment by PierrotIV** [comment]
I have detailed it in issues #52 and #54 
Btw, I added a fix, could you please push it to next release ?

**Comment by DevineLykan** [comment]
Hey!

I don’t actually look after the addon. I just know how to do lua scripting
so fixed something that wasn’t working for me!

But I can take a look when I have some free Time.

**Comment by PierrotIV** [comment]
Ok, sorry, I thought you were taking up the work in progress ;)
Let's hope @robert388 reads us and will include those fixes.

**Comment by PierrotIV** [comment]
Fixed in 6.4
