### ISSUE TITLE
Addon is Not Working At All

### ISSUE THREAD

**Issue by DevineLykan** [robert388/Necrosis-classic#59]
You've broken it XD

Can't even get into the addon anymore

**Comment by robert388** [comment]
What i did was i put the latest of master online. I just applied a fix. If this still not fixes the issues we are gonna roll back to v5.1.

**Comment by robert388** [comment]
Wich is this commit https://github.com/robert388/Necrosis-classic/commit/eedf621fb801e3b42aeea1071e016de0ecefaf23

**Comment by DevineLykan** [comment]
@robert388 current version is more stable, however, you have to /reloadui to get it working, so something is causing it to miss load first time, and the mount button won't let you dismount anymore.

**Comment by DevineLykan** [comment]
fixed in re-work of code
