### ISSUE TITLE
Necrosis.lua:1961: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by PierrotIV** [robert388/Necrosis-classic#93]
Message: Interface\AddOns\Necrosis\Necrosis.lua:1961: attempt to concatenate a nil value
Time: Fri Dec 13 11:58:02 2019
Count: 1
Stack: Interface\AddOns\Necrosis\Necrosis.lua:1961: attempt to concatenate a nil value
...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:732: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:692>
(tail call): ?
[C]: ?
Interface\AddOns\Necrosis\Necrosis.lua:1961: in function `BagExplore'
Interface\AddOns\Necrosis\Initialize.lua:151: in function `Initialize'
Interface\AddOns\Necrosis\Necrosis.lua:355: in function `OnLoad'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: errMsg = "Interface\AddOns\Necrosis\Necrosis.lua:1961: attempt to concatenate a nil value"
tsmErrMsg = nil
oldModule = nil
private = <table> {
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:513
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:132
 hitInternalError = false
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:295
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:494
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:479
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:487
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:327
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:379
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:455
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:296
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by Debokitty** [comment]
got same issue

**Comment by Debokitty** [comment]
necrosis doesnt work any more, sad :(

**Comment by PierrotIV** [comment]
Fixed in 6.4
